### ISSUE TITLE
Plugin crashing at server start.

### ISSUE THREAD

**Issue by marioogg** [ElCholoGamer/userlogin#48] opened 2022-12-31 15:59 UTC
The server crashes everytime i open my auth serve with the userlogin, server type: PaperMC 1.8.8
Error: 
[10:38:43 INFO]: [UserLogin] Enabling UserLogin v2.13.0
[10:38:43 ERROR]: Error occurred while enabling UserLogin v2.13.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.FileConfiguration.contains(Ljava/lang/String;Z)Z
        at com.elchologamer.userlogin.manager.LangManager.createDefault(LangManager.java:49) ~[?:?]
        at com.elchologamer.userlogin.manager.LangManager.reload(LangManager.java:65) ~[?:?]
        at com.elchologamer.userlogin.UserLogin.reloadPlugin(UserLogin.java:124) ~[?:?]
        at com.elchologamer.userlogin.UserLogin.onEnable(UserLogin.java:47) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]

**Comment by BratishkaErik** [comment] 2023-01-08 08:02
Duplicate of #39

**Closed as not planned** 2024-07-10 13:38 UTC
